version: "3.9"

services:
  db:
    image: postgres:16
    container_name: feuerwehr-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: feuerwehr
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: feuerwehr-app
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/feuerwehr
    command: sh -c "npx prisma migrate deploy && npm run start"

volumes:
  db_data:
