version: "3.9"

services:
  feuerwehrdb:
    image: docker.io/library/mysql:latest
    container_name: feuerwehrdb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: feuerwehr
      MYSQL_USER: feuerwehr
      MYSQL_PASSWORD: feuerwehr
    ports:
      - "3306:3306"
    networks:
      - testanet
    volumes:
      - db_data:/var/lib/mysql

#  prisma-migrate:
#    build:
#      context: ../../
#      dockerfile: Dockerfile
#    container_name: prisma-migrate
#    depends_on:
#      - feuerwehrdb
#    networks:
#      - testanet
#    env_file:
#      - ../../.env
#    command: >
#      sh -c "
#      echo '⏳ waiting for db...' &&
#      sleep 10 &&
#      npx prisma generate &&
#      npx prisma migrate deploy
#      "

#  feuerwehrapp:
#    build:
#      context: ../../
#      dockerfile: Dockerfile
#    container_name: feuerwehrapp
#    depends_on:
#      - prisma-migrate
#    networks:
#      - testanet
#    ports:
#      - "3000:3000"
#    environment:
#      DATABASE_URL: mysql://feuerwehr:feuerwehr@feuerwehrdb:3306/feuerwehr
#    command: sh -c "sleep 10 && npx prisma migrate deploy && npm run start"

volumes:
  db_data:

networks:
  testanet:
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: "2001:db8:1::/64"
