version: "3.9"

services:
  feuerwehrdb:
    image: docker.io/library/mariadb:latest
    container_name: feuerwehrdb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: feuerwehr
      MARIADB_USER: feuerwehr
      MARIADB_PASSWORD: feuerwehr
    ports:
      - "3306:3306"
    networks:
      - testanet
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:

networks:
  testanet:
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: "2001:db8:1::/64"